### PR TITLE
[FEATURE] Funds.source_transfer_ledger

### PR DESCRIPTION
**Pull request by sentientwaffle**

### CODE REVIEW

**Comment by justmoon** [comment]
This should go into a memo field on the Debit instead in my opinion.

**Comment by sentientwaffle** [comment]
@justmoon ok, `memo` is just a plain object now.

**Comment by emschwartz** [comment]
Yeah, if the connector (or any other party) is going to include "notes to self" that don't affect other participants, we shouldn't include them in the standard/schemas

**Comment by emschwartz** [comment]
LGTM

**Pull request merged**
