### PR TITLE
Use 2048bit RSA keys for JCS test

### PR DESCRIPTION
**Pull request by lumberj**
~100ms vs. ~500ms to sign with a 4096bit key

```
  jsonSigningTests
    jsonSigning
      ✓ should sign JSON object successfully (66ms)
    jsonSignAndVerify
      ✓ should sign and verify JSON object successfully (96ms)
    jsonInvalidSignature
      ✓ should catch invalid JSON signature
    jsonInvalidPublicKey
      ✓ should catch invalid public key in signed JSON
    jsonRSASigning
      ✓ should sign JSON object with RSA successfully (93ms)
    jsonRSASignAndVerify
      ✓ should sign and verify JSON object with RSA successfully (92ms)
    jsonRSAInvalidSignature
      ✓ should catch invalid JSON signature with RSA (75ms)
    jsonRSAInvalidPublicKey
      ✓ should catch invalid RSA public key in signed JSON (76ms)

  8 passing (573ms)
```

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
What's the motivation for this? Speeding up the tests?

**Comment by lumberj** [comment]
Yes, and also we'll be using 2048bit RSA keys for notification signing for now

**Comment by naoitoi** [comment]
Quick Googling netted several good sources saying 2048 bit RSA key is secure enough, for now:
http://www.emc.com/emc-plus/rsa-labs/historical/has-the-rsa-algorithm-been-compromised.htm
https://www.yubico.com/2015/02/big-debate-2048-4096-yubicos-stand/
So it's fine to use 2048 bit key for testing. 
LGTM

However, in production, customers may require 4096 bit keys, so we still should find a faster alternative to jsrsasign.

**Comment by lumberj** [comment]
There is a ticket to track that. I copied you on it

**Pull request merged**
