### PR TITLE
Remove unused transfer states

### PR DESCRIPTION
**Pull request by MatthewPhinney**

### CODE REVIEW

**Comment by clark800** [comment]
LGTM

**Comment by MatthewPhinney** [comment]
@emschwartz could you give some more context here? The pre* states were removed from the ledger here: https://github.com/interledger/five-bells-ledger/commit/acc395db4c586469fa0474dc5d1ed7cf10467d90. I don't think  `failed` is used for anything, so I'd like to remove that from the ledger, as well. I discussed with Stefan, and we decided to have `rejected` be the only failed state. We'll add a `rejected_reason` to the transfer, so users can tell if it was cancelled or expired. `nonexistent` looks like it's used, so I'll add that back in.

**Comment by justmoon** [comment]
`failed` can be safely removed. It was intended to be used for internal errors in the ledger. No appropriate use case for it has come up so far and if it does, `state = "rejected"` with `rejection_reason = "failed"` would be better anyway.

`nonexistent` is still needed for the time being. It's only used in transfer receipts though, so we could remove it from `TransferState.json` and change the `state` field in `TransferStateReceipt.json` to:

``` json
{
  "oneOf": [{
    "$ref": "TransferState.json"
  }, {
    "enum": ["nonexistent"]
  }]
}
```

**Comment by MatthewPhinney** [comment]
I like this solution. I added `nonexistent` to `TransferStateReceipt`.

**Comment by MatthewPhinney** [comment]
@justmoon please confirm that this looks OK to you.

**Comment by justmoon** [comment]
LGTM

**Pull request merged**
